apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-crud
spec:
  replicas: 1  # Single replica for dev
  template:
    spec:
      containers:
      - name: fastapi-crud
        image: docker4mlops/fastapi-crud:v2  # Use your Docker image here
        ports:
        - containerPort: 8000
