apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-crud
spec:
  replicas: 3  # 3 replicas for production
  template:
    spec:
      containers:
      - name: fastapi-crud
        image: docker4mlops/fastapi-crud:v1  # Use your Docker image here
        ports:
        - containerPort: 8000
